name: Western

cues: []

triggers:
  - name: start
    pin: 2
    to: low
    once: true
    do:
      - { at: 0, action: audio, file: sounds/detective.mp3, loop: true, replace: true }
      - { at: 0, action: video, file: video/diamante.mp4, loop: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)"}
  - name: film
    uid: "6A003E82F0"
    once: false
    do:
      - { at: 0, action: morse, pin: 9, message: "RAIN", unit: 0.2, loop: true }
      - { at: 0, action: audio, file: sounds/western1.mp3, loop: true, replace: true }
      - { at: 0, action: video, file: video/condensa.mp4, loop: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)" }
  - name: error
    pin: 3
    to: low
    once: true
    do:
      - { at: 0, action: morse, pin: 9, message: "HOT", unit: 0.2, loop: true }
      - { at: 0, action: audio, file: sounds/morricone.mp3, loop: true, replace: true }
      - { at: 0, action: video, file: video/desert.mp4, loop: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)" }
  - name: stop
    pin: 8
    to: low
    once: true
    do:
      - { at: 0, action: stop_all }
