name: Fantasy

cues: []

triggers:
  - name: start
    pin: 2
    to: low
    once: true
    do:
      - { at: 0, action: video, file: video/bollywood.mp4, loop: true, volume: 0.8, backend: mpv, screen: Built-in Retina Display }
  - name: film
    uid: "6A003E82F0"
    once: false
    do:
      - { at: 0, action: morse, pin: 9, message: "MATRIX", unit: 0.2, loop: true }
      - { at: 0, action: audio, file: sounds/matrix.mp3, loop: true, replace: true }
      - { at: 0, action: video, file: video/matrix.mp4, loop: true, replace: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)" }
  - name: error
    pin: 3
    to: low
    once: true
    do:
      - { at: 0, action: morse, pin: 9, message: "COMIC", unit: 0.2, loop: true }
      - { at: 0, action: video, file: video/fantasy.mp4, loop: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)" }
      - { at: 0, action: audio, file: sounds/fantasy.mp3, loop: true, replace: true }
  - name: stop
    pin: 8
    to: low
    once: true
    do:
      - { at: 0, action: stop_all }
