name: Bollywood

cues:
  - { at: 0, action: audio, file: /Users/lussoluca/Sites/Personal/vdb2026/sounds/516905__rakkarage__error.wav, loop: true }
  - { at: 0, action: video, file: video/0_Glitch_Glitch_Effect_3840x2160.mp4, loop: true, volume: 0.8, backend: mpv, screen: Built-in Retina Display }

triggers:
  - name: error
    pin: 2
    to: low
    once: true
    do:
      - { at: 0, action: stop_audio }
      - { at: 0, action: morse, pin: 9, message: "SOS", unit: 0.2, loop: true }
      - { at: 0, action: audio, file: sounds/859449__coghezzi__alien-ship-alarm-escape-detected.wav, loop: true }
      - { at: 0, action: video, file: video/0_Neon_Number_3840x2160.mp4, loop: true, volume: 0.8, backend: mpv, screen: Built-in Retina Display }
  - name: unlock
    uid: "6A003E764C"
    once: false # fire on every scan of this card
    do:
      - { at: 0, action: "on", pin: 9 }
      - { at: 0, action: audio, file: sounds/516905__rakkarage__error.wav, loop: true }
  - name: stop
    pin: 8
    to: low
    once: true
    do:
      - { at: 0, action: stop_all }
