name: Giallo

cues:
  - { at: 0, action: audio, file: sounds/odissea_spazio.mp3, loop: true }
  - { at: 0, action: video, file: video/giallo1.mp4, loop: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)" }

triggers:
  - name: unlock
    uid: "6A003E764C"
    once: false
    do:
      - { at: 0, action: morse, pin: 9, message: "OK", unit: 0.2, loop: true }
      - { at: 0, action: video, file: video/rec.mp4, loop: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)" }
      - { at: 0, action: audio, file: sounds/giallo.mp3, loop: true, replace: true }
  - name: black
    pin: 2
    to: low
    once: true
    do:
      - { at: 0, action: morse, pin: 9, message: "SOS", unit: 0.2, loop: true }
      - { at: 0, action: video, file: video/ladro.mp4, loop: true, volume: 0.8, backend: mpv, screen: "Sidecar Display (AirPlay)"}
  - name: stop
    pin: 8
    to: low
    once: true
    do:
      - { at: 0, action: stop_all }
